spring:
  application:
    name: SpinTrail
  datasource:
    url: jdbc:postgresql://localhost:5432/spintrail
    username: postgres
    password: Sohan$1977
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Add these — needed later for routing API
routing:
  openrouteservice:
    api-key: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImI1YTYzMzk2MDc5MjQ2MjI5ZDUxYjRiZDQwNGZkZWM5IiwiaCI6Im11cm11cjY0In0=
    base-url: https://api.openrouteservice.org/v2/directions/cycling-regular

kind: Application