spring:
  application:
    name: SpinTrail

  datasource:
    url: jdbc:postgresql://localhost:5432/spintrail
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

routing:
  openrouteservice:
    api-key: ${ORS_API_KEY}
    base-url: ${ORS_BASE_URL}

geocoding:
  nominatim:
    base-url: ${NOMINATIM_BASE_URL}
    user-agent: ${NOMINATIM_USER_AGENT}